language: r
sudo: false
cache: packages
r_packages:
- testthat
- covr
after_failure:
  email:
    recipients:
     - john@fpsignals.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
